---
# defaults file for disconnected_registry
install_config_appends_file: install-config-appends.yml
registry_auth_file: registry-auths.json
disconnected_registry_user: dummy
disconnected_registry_password: dummy
