---
- name: Validate Assisted Installer Deployment Environment
  hosts: assisted_installer
  vars:
    version: 4.6.13
  roles:
  - okd.assisted_installer.disconnected_registry
  tags:
  - create_registry
  - all
