galaxy_info:
  author: Roger Lopez
  description: Create discovery ISO for Assisted Installer
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
